### ISSUE TITLE
[Bug] Outputs still use old repo name in the dist/ files

### ISSUE THREAD

**Issue by jgleonard-takeda** [austenstone/job-summary#8]
### What happened?

You need to update the dist/ folder in the main branch to match the code.  It doesn't appear to have been rebuilt since the repo name change.  The outputs, specifically md-file, have the wrong file path.

### Relevant log output

```shell
File not found at path '/home/runner/work/_actions/austenstone/job-summary/main/dist/job-summary-to-pdf/job-summary.md'
```

### Contact Details

jon.leonard@takeda.com

**Comment by austenstone** [comment]
I changed the repo name from `job-summary-to-pdf` to `job-summary` and it caused failures.

```yml
      - uses: austenstone/job-summary@v2.0
```

This should work now.
https://github.com/austenstone/copilot-usage/actions/runs/9026479619/job/24803848523

**Comment by jgleonard-takeda** [comment]
Sorry, no good. Check the dist. The md-file output is still incorrect. 

```File not found at path '/home/runner/work/_actions/austenstone/job-summary/v2.0/dist/job-summary-to-pdf/job-summary.md'```

**Comment by jgleonard-takeda** [comment]
@austenstone please review the steps that I posted to confirm

**Comment by austenstone** [comment]
I noticed tag `v2.0` was still missing the build but main has it.

https://github.com/austenstone/job-summary/blob/main/dist/index.js

**Comment by jgleonard-takeda** [comment]
@austenstone The issue is present in the main branch as well at the link you provided.  See the md-file and html-file outputs.

```
    (0,core.setOutput)('pdf-file', external_path_default().resolve(`${input.name}.pdf`));
    (0,core.setOutput)('md-file', __nccwpck_require__.ab + "job-summary-to-pdf/" + input.name + '.md');
    (0,core.setOutput)('html-file', __nccwpck_require__.ab + "job-summary-to-pdf/" + input.name + '.html');
    ```
